src/extensions/renderer.canvas.define-and-init-etc.js

Hi, this PR fix the leaked div reported on #793 that is used to calculate the label dimensions.
This div is appended to the body at the init and it's never removed or reused during the cy.destroy().
I'm not sure if this is the best way to solve this issue. Maybe it can be better to add the labelCalcDiv into the current cytoscape container (not into the body) and remove everything during the destroy changing the line https://github.com/cytoscape/cytoscape.js/blob/master/src/extensions/renderer.canvas.coord-ele-math.js#L659 with the following:
this.data.container.appendChild( div );

fix #793 leaked labelCalcDiv used to calculate label dimensions

---

documentation/md/collection/map.md

Hi - this updates the the example for `eles.map()` so that it logs the defined variable.
Regards,
Szymon

Log correct variable in map example.

---

src/extensions/layout.springy.js

https://github.com/dhotson/springy/issues/39
The length can be set on edge objects. ie edge.data.length
If the length property exists it will be used in the physics calculations (default length is 1).

Add length property to springy edge

---

src/extensions/renderer/base/load-listeners.js

Use desktopTapThreshold for all mouse drag functionality.
Related external bug: https://bugs.chromium.org/p/chromium/issues/detail?id=161464
Because of the aforementioned bug in Chromium (which apparently only affects Windows users), all events that rely on there not being a `mousemove` event, such as `taphold` and `cxttap` (these were the only 2 I tested), fail to trigger.
As pointed out in the external bug report, a simple solution and good practice when dealing with these click + move interactions is to only consider a drag after a certain movement threshold. Such a threshold already exists (`desktopTapThreshold`) but is only applied when testing dragging of nodes. Because cancellation of holds and right taps occurs outside of this test, the problem manifests.
For the fix, testing …

Fix taphold and cxttap problems under Chrome for Windows.

---

src/index.js

Some build steps error out when trying to require the version file, this adds .json to the end of the file to be more specific in the require call.
For issue: https://github.com/cytoscape/cytoscape.js/issues/1394

Changes the require of the version file

---

documentation/md/events.md
src/core/index.js
test/events.js

Adds a `destroy` event which is triggered right **after** the instance was destroyed.
Allows external loops (like animated layouts) to listen to calls of `.destroy()`. Should provide the basis for future fixes for #1499 and related issues.
In addition to the event this PR also adds an `isDestroyed()` method (similar to `isReady()`) to check the state. This also allows for `.destroy()` to get called multiple times, as they can be safely ignored.

add 'destroy' event & provide info if already destroyed

---

documentation/md/style.md
src/extensions/renderer/base/images.js
src/extensions/renderer/canvas/drawing-nodes.js
src/style/properties.js

Allows the crossorigin attribute on image requests to be changed using styles. Fixes https://github.com/cytoscape/cytoscape.js/issues/1607
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin
https://github.com/cytoscape/cytoscape.js/issues/1607

Add `background-image-crossorigin` style

---

debug/init.js
src/collection/dimensions.js
src/style/properties.js

- adds optional min-width, min-height properties for compound nodes
- computes autoWidth based on maximum of the boundingBox and min-width/height values
- adds commented out properties to the init script in the debug app
@maxkfranz @metincansiper @ugurdogrusoz 
Related issues: 
https://github.com/cytoscape/cytoscape.js/issues/1614
https://github.com/iVis-at-Bilkent/chise.js/issues/66
**Testing**
I have tested the following cases on the debug app:
width:
* left-bias > right-bias
* right-bias > left-bias
* left-bias = right-bias
* the above cases applied with left-bias+right-bias > 100
* the above cases applied with left-bias+right-bias < 100
* case when padding is not 0
* case when left-bias + right-bias = 0
height:
* the same cases applied mentioned above applied to height and its …

`min-width`, `min-height` properties for updating compound bounds. #1614

---

src/collection/dimensions.js
src/style/properties.js

* Adds px support for the min-\*-bias-\* property values for compound nodes
* Refactors the code in compoundBounds calculation to reduce the amount of repeated code
* Adds a new pxPercentSize property type -- a size type that also supports percentages 
* Px values for the bias fields are converted to percentages before the compoundBound calculation
The following cases have been tested on the cytoscape.js debug app:
* min-width/min-height set to 0
- bias values set to 0
- bias values set > 0
* min-width set to > 0
- left bias px + right bias % > min-width
- left bias px + right bias % < min-width
- left bias px + right bias % = min-width
- left bias px + right bias px > min-width
- left bias px + right bias px < min-width
- left bias px + right bias px = min-width
- left bias % + right …

add px support for compound bias properties

---

src/extensions/renderer/base/arrow-shapes.js

Update to #1672. Produces good results for `arrow-scale` > 0.5. Below 0.5 scaling, the edges of the edge will protrude from the side of the `triangle-backcurve` shape (as well as the `vee` shape). The scaling value of 0.985 (times the standard scaling value) is a trade-off made for all shapes with concave bases.
As scaling values approach 0, the shape becomes significantly smaller than its edge, so it becomes impossible to fully hide the edge behind the arrow (and placing the shape at the tip of the edge, as is done for other shapes, leaves empty space in the concave region of the shapes). 
Demo of new changes: http://jsfiddle.net/josephst18/rkd4bLs4/8/

Update gap calculation for triangle-backcurve and vee

---

src/extensions/renderer/base/arrow-shapes.js
src/extensions/renderer/canvas/arrow-shapes.js
src/extensions/renderer/canvas/drawing-edges.js
src/style/properties.js

- implements a new arrow head shape called 'triangle-cross'
- collision detection using inline vicinity
- scales arrow size based on edge width and size
- removes explicit arrowShape check for 'half-triangle-overshot' in the drawArrowHead function
- reuses arrowWidth and arrowShape variables that were already computed at the beginning of the drawArrowHead function
- shapeImpl.draw takes edgeWidth as a parameter for arrow scaling
See https://github.com/cytoscape/cytoscape.js/issues/1656

Triangle-cross arrowhead

---

src/collection/layout.js
src/extensions/layout/breadthfirst.js
src/extensions/layout/circle.js
src/extensions/layout/concentric.js
src/extensions/layout/cose.js
src/extensions/layout/grid.js

I've tentatively named the option scalingFactor rather than spacingFactor as the `breadthfirst` layout option already includes a spacingFactor option. This PR adds a `scalingFactor` option that multiplies the layout-calculated position of the node by the (absolute value of the) `scalingFactor` to produce a final position to be rendered. 
Ex: a layout which spaces nodes out by 50px will have 100px gaps between nodes when `scalingFactor` is 2.

Add scalingFactor for adjusting layouts post-calculation #1266

---

documentation/md/events.md

Emitted when viewport is (re)rendered

document the 'render' event

---

documentation/md/style.md
src/extensions/renderer/base/coord-ele-math.js
src/extensions/renderer/base/node-shapes.js
src/extensions/renderer/canvas/drawing-shapes.js
src/extensions/renderer/canvas/node-shapes.js
src/math.js
src/style/properties.js
src/util/index.js

- cutrectangle shape can be a compound or simple node
- adds a util.push method for arrays
- refactors math.polygonIntersectLine to allow polygon intersect
checking without transforming the base points
- adds 'cutrectangle' to nodeshape enums
- adds comments for ambiguous arguments in some math functions

implements cutrectangle node shape

---

src/util/timing.js

IE9 has `window` defined but none of the `requestAnimationFrame` properties so we end up with an `undefined` `raf` variable and cytoscape breaks whenever `util.requestAnimationFrame` is called.
I reordered the variable assignment a bit to use the "no window" value as a default value whenever all the `requestAnimationFrame` properties don't exist.

Make sure raf is defined to fix IE9 issue.

---

documentation/docmaker.json
documentation/md/collection/layoutPositions.md

Addresses #1765. 
Should `eles` be included in the description of options?

Describe layoutPosition() options

---

src/collection/dimensions.js
src/extensions/renderer/base/node-shapes.js

Changed the height computation to add the bias bottom and subtract the bias top instead of the other way around.
Ellipse check point method was broken because I was just calling Math.checkInEllipse instead of returning the result.

fix min-height bottom/top properties working in reverse; fix ellipse check point bug introduced in earlier commit

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md

Adds a template for new issues and changes to the `contributing.md` file to point to the blog post (not yet published).

Add contributor guides to accompany blog post

---

src/extensions/renderer/canvas/drawing-shapes.js
src/math.js

Related: https://github.com/cytoscape/cytoscape.js/issues/1884
Fixes child nodes going outside of the parent shape.
Before:

Barrel shape: set max values for curve width/height offsets

---

src/core/viewport.js

Fixes issue #1965 
Other alternatives could replace the `is.elementOrCollection( elements ) && ...` by `is.fn( elements.empty ) && ...` or `typeof elements.empty === 'function' && ...`.

Fix unwanted empty() call on boundingBox

---

src/collection/class.js
src/collection/element.js
test/collection-style.js

This implements #1644. I think this is just about ready, but I wanted to open it up for maintainer input before going any farther.
Do you have any opinions on what to do with arrays of strings with spaces in them - e.g.
```
[ 'foo', 'bar baz' ]
```
This PR takes care of classes at initialization, `eles.classes()`, `eles.addClass()`, `eles.removeClass()`, and `eles.toggleClass()`. Is there anything else that needs to support arrays of classes?

Allow classes to be specified as arrays #1644

---

src/extensions/renderer/canvas/drawing-edges.js
src/style/properties.js

This pull request adds the feature to specify the edge cap (shape of the edge endings) as proposed in issue #1948. This is important to avoid "cracks" between edges when nodes are smaller than the edge width or hidden. 
Since it is based on the canvas property `line-cap`, it should not have significant impact on performance.

Add property edge-cap

---

src/extensions/renderer/canvas/drawing-nodes.js

Max and Dylan : Fixing cytoscape issue that is reproducible within pc/app-ui.
This affects svg background images that are drawn by Dylan's sbgn-stylesheet lib.
With this change, app-ui can use cytoscape@#unstable to run the latest code.
See  #2049 for more info

3.3.0-unstable does not position bg images properly if two nodes share dims #2049

---

src/extensions/renderer/base/node-shapes.js

- uses static t value to calculate quad bez pts
- value set to 0.4 as it seemed the most accurate
addresses #1874
pics:

Slightly better approximation of barrel curve pts for line intersection

---

documentation/demos/6000-elements/index.html
documentation/demos/animated-bfs/index.html
documentation/demos/architecture/index.html
documentation/demos/circle-layout/index.html
documentation/demos/cola-compound/index.html
documentation/demos/compound-nodes/index.html
documentation/demos/concentric-layout/index.html
documentation/demos/cose-bilkent-layout-compound/index.html
documentation/demos/cose-bilkent-layout/index.html
documentation/demos/cose-layout/index.html
documentation/demos/dagre-layout/index.html
documentation/demos/edge-types/index.html
documentation/demos/genemania-export/index.html
documentation/demos/grid-layout/index.html
documentation/demos/images-breadthfirst-layout/index.html
documentation/demos/initialisation/index.html
documentation/demos/labels/index.html
documentation/demos/linkout-example/index.html
documentation/demos/multiple-instances/index.html
documentation/demos/performance-tuning/index.html
documentation/demos/pie-style/index.html
documentation/demos/spread-layout/index.html
documentation/demos/visual-style/index.html

The same comment , where present, has the word 'application' misspelled in the demos directory. Fixed by applying the following search & replace pattern: s/appplication/application/

Fixed redundant typo (appplication -> application) in demos

---

.size-snapshot.json
package-lock.json
rollup.config.js

Since both `umd` and `min` bundles are identical there is not reason to
make a snapshot of them both.

Remove useless minified bundle size snapshot

---

.size-snapshot.json
package.json
rollup.config.js

Sometimes it's easy to forget to run build and commit snapshot. This
leads to unobjective differences in snapshots in further commits.
`matchSnapshot` option allows to fail if existing commit and generating
one are not matched. This is useful to fail on CI.

Fail on CI if size snapshot is not updated

---

.travis.yml
src/core/viewport.js
test/core-init.js

This PR includes a fix for #2245 maxZoom initialisation option has no effect.
In `zoomRange()` when only `maxZoom` is set, then max should be >= _p.minZoom instead of `max <= _p.minZoom`

#2245 Fix broken maxZoom setting

---

src/core/index.js
test/core-graph-manipulation.js

eles.move(...) creates a copy of the elements to be "moved" and
deletes the originals, thus we need to check if we need to remove the
new elements.
Targeting master as this is a bugfix

cy.json should remove the contents of compounds nodes.

---

src/style/apply.js
src/style/parse.js

This PR includes two proposed performance optimizations to styling, specifically for mapped properties.
Optimization 1:
* Mapped properties for contexts an element doesn't have still get flagged as ```diffProps``` and are processed as such only to get "deleted" (those properties won't get set in ```getContextStyle```) from the style later . The optimization catches this case earlier in the styling process.
* Specific changes: In ```getPropertiesDiff```, only consider a context if 1) the context has changed, or 2) if the element has the context and the context has mapped properties (case 2 contains the new behavior).
Optimization 2:
* Mapped properties get recomputed and reapplied every time regardless of whether they changed or not. The optimization caches the previous, un-parsed value …

Optimizations for mapped style properties

---

src/extensions/renderer/canvas/index.js

Hi!
I'm a bit focused on security, so my webservers all run with a very strict Content-Security-Policy; currently it's set to:
> Content-Security-Policy: default-src 'none'; img-src 'self'; script-src 'self'; prefetch-src 'self'; worker-src 'self'; connect-src 'self'; style-src 'self'
With current unstable, Chrome will refuse some style applications with the message:
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'".
I've changed `src/extensions/renderer/canvas/index.js` to apply the style without triggering the error.
Please check that the changes do not change behaviour, I'm not confident with JavaScript, yet.
There is another problem that I cannot figure out by myself: …

change style application to satisfy CSP style-src 'self'

---

src/core/animation/step.js
test/core-graph-manipulation.js

We are using cytoscape within a React application. We noticed that when 2 nodes were at least 15,000 units apart, a `fitSelected` followed by a `fit` would cause cytoscape to crash.
What is happening is that `new OffscreenCanvas(NaN, NaN)` is being invoked because `zoom` is temporarily a negative number which makes `lvl` equate `NaN`.
https://github.com/cytoscape/cytoscape.js/blob/85f0c8dfebc3ed9796651fef43be7ff871db88ce/src/extensions/renderer/canvas/layered-texture-cache.js#L118
The reason why `lvl` is a `NaN` is because `Math.log` and `Math.log2` result in `NaN` at negative values.
```js
Math.log2(1) // 0
Math.log2(0) // -Infinity
Math.log2(-1) // NaN
```
This explains why the docs specifically mention that `zoom` must be positive. …

Zoom animation can cause zoom value to be outside of [minZoom, maxZoom]

---

package.json

This PR adds [unpkg](https://unpkg.com/) & [jdelivr](https://www.jsdelivr.com/) fields, so AMD loaders like d3-require can load cytoscape.js in a web browser. The UMD builds already exist (yay), so this just configures them to be used.

Add unpkg and jsdelivr entry points

---

src/extensions/layout/cose.js

There is a very slight bug in the cose layout that components that are already separate are again separated when a layout is re-run. If you perform a cose layout, then use that as the starting position to perform another layout, the components separate even more. If you keep re-doing the layout, the components keep on separating. This leads to bigger and bigger separations on re-layouts. This can be undone by offsetting the component separation by the x1 and y1 of the component.

COSE offset component separation by left-top of component

---

src/extensions/layout/breadthfirst.js

Breadthfirst orders nodes by their connections to their predecessors, but in case of a tie uses the nodes' IDs. However, in the case of a particular depth having only 1 node, there is a division by 0 and all that node's successors have a weight of NaN, causing them to be ordered arbitrarily.
A minimal example of this problem:
https://jsfiddle.net/sLx814y5/
This does not match my expectation of child 1-3 being in order from left to right.
Being able to control the order of nodes in this way is very useful to me but I can't control it in this scenario.

Breadthfirst layout ordering

---

documentation/md/getting-started.md

PageCDN uses brotli-11 compression that reduces cytoscape's file sizes by upto 28 KBs compared to other CDNs. In addition, immutable caching is enabled by default to optimize content delivery a little more aggressively. This will make PageCDN a valuable addition to the documentation.
Thanks.

Added new CDN - PageCDN

---

src/extensions/renderer/base/coord-ele-math/edge-control-points.js

When a self-loop was inside a compound, the findCompoundLoopPoints took precedence over the self-loop, thus `loop-direction` and `loop-sweep` values were ignored.
@maxkfranz is there any reason to have the compound check before the self-loop check?

Check self-loop before compound-loop

---

documentation/demos/node-types/data.json
documentation/md/style.md
src/extensions/renderer/base/node-shapes.js
src/extensions/renderer/canvas/drawing-shapes.js
src/extensions/renderer/canvas/node-shapes.js
src/math.js
src/style/properties.js

Feature request: Add the following rounded node shapes: round-triangle, round-diamond, round-pentagon, round-hexagon, round-heptagon, round-octagon, round-tag
OP follows:
-- 
I would like to add a new shape, would something like this be accepted into the code base (once finished)?

Rounded polygon shapes (e.g. `round-triangle`)

---

src/extensions/renderer/base/coord-ele-math/labels.js

If you try to create a label with long unsplittable name in the first line, it tries to split it, push an empty line as first line and renders the whole string in the second line.
This PR adds the logic to avoid to render the first line empty in the label.

Fix label split so to avoid to render empty lines

---

documentation/docmaker.json
documentation/md/collection/hierholzer.md
package.json
src/collection/algorithms/hierholzer.js
src/collection/algorithms/index.js
test/collection-hierholzer.js

This pull request adds Hierholzer's algorithm as proposed in issue [#2186](https://github.com/cytoscape/cytoscape.js/issues/2186) (recently closed, presumably due to inactivity). In particular, it can find Eulerian trails and cycles in both directed and undirected multigraphs should they exist.
For the sake of transparency, it should be known that I am new to the PR game and as such am anticipating potentially extensive feedback for this contribution, although I've attempted to do my due diligence.

Add Eulerian trail search algorithm

---

documentation/md/collection/hierholzer.md

When I wrote the hierholzer example in the documentation I was unaware of the fact that, on the official js.cytoscape.org page, the user could actually run this code snippet in their browser (neat!) 
Unfortunately the selector I arbitrarily chose here causes an error to be thrown in the console (which is to be expected since no eulerian trail exists starting from this node). 
The good news however is that this was easily rectified. My apologies.

Fix hierholzer example

---

documentation/md/collection/collection.md
src/collection/index.js
src/collection/iteration.js
test/collection-iteration.js

This PR implements an iterable behaviour for collections, as proposed in issue [#1365](https://github.com/cytoscape/cytoscape.js/issues/1365).
In terms of writing documentation for this some soft guidance would be greatly appreciated, as this falls a bit outside of the eles.method(...) convention.

Iterable support for collections

---

debug/init.js
documentation/index.html
documentation/md/style.md
src/extensions/renderer/base/coord-ele-math/edge-control-points.js
src/style/properties.js

A negative value specifies a distance relative to the target side (from target to source) rather than the default source side (from source to target).

Add support for negative `taxi-turn` values

---

documentation/md/collection/hopcroftTarjanBiconnected.md
src/collection/algorithms/hopcroft-tarjan-biconnected.js
test/collection-hopcroft-tarjan-biconnected.js

In the current implementation of the `buildComponent` function within `eles.htbc()` there is a flaw such that, for certain graphs, a singular edge (or multiple, counting loops) will be omitted from a `components` collection during it's respective construction. A minimal reproducible example of this behaviour can be seen [here](https://codepen.io/r-ba/pen/jOPObZz). The intent of this PR is to amend this issue.

Patch `buildComponent` in `eles.htbc()`

---

documentation/index.html
documentation/md/getting-started.md

**Issue type**
Documentation bug report
**Current (buggy) behaviour**
Since version 2.7.0, edges are haystack by default, which only support midpoint arrows. The example is supposed to show an arrow and it doesn't.
**Desired behaviour**
I have added a curve style that allows it to be shown.

Add curve-style: bezier to the tutorial example

---

src/collection/algorithms/betweenness-centrality.js
test/collection-algorithms.js

**Issue type**
Bug report
I have noticed a bug in the part of Betweenness Centrality when shortest paths are aggregated. For the graph as in this example:
https://jsbin.com/rijavenodo/1/edit?html,css,js,console,output
(this is also the graph I put in a new test) calculated value for node `e` (red one) is 4, but it should be 3 (because `e` lies on all shortest paths between pairs `(a, c)`, `(b, c)` and `(d, c)`).

Bugfix in Betweenness Centrality

---

dist/cytoscape.cjs.js
dist/cytoscape.esm.js
dist/cytoscape.umd.js
documentation/index.html
src/extensions/layout/concentric.js

I think what probably happened was someone originally wrote "variation" and then there was a search and replace for /^var/ to "let" 😂

Fix typo in example code comment (letiation -> variation)

---

src/extensions/renderer/base/coord-ele-math/labels.js

- Fixes cytoscape/cytoscape.js#2761
- New logic will first test if the full label fits in the node, if it does, use the full label. Otherwise, the old logic will apply since we know we are going to be using ellipsis (label doesn't fit).

Change ellipsis label logic

---

package.json

https://github.com/cytoscape/cytoscape.js/blob/unstable/README.md#build-instructions
According to docs "npm run benchmark" should run all benchmarks, but currently only runs single benchmark.
This was changed so that it aligns with the docs.

"npm run benchmark" runs all benchmarks

---

documentation/demos/tokyo-railways/index.html

Firefox blocks loading of http scripts on  https pages by default, resulting in a broken demo.
See https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#Types_of_mixed_content
**Issue type**
Issue on the website
**Current (buggy) behaviour**
Demo doesn't load in firefox
**Desired behaviour**
Demo should load in firefox
**Minimum steps to reproduce**
1. Open https://js.cytoscape.org/demos/tokyo-railways/ in firefox
2. Open console and see the warning about mixed content

Use only https assets in tokyo-railways demo

---

debug/FileSaver.js
documentation/md/core/json.md
src/core/index.js

Closes #2805. Also fixes a typo in `debug/FileSaver.js` i randomly stumbled upon.
(I added an continue statement to skip elements without IDs, as they were previously added just to be removed again)

Clarify that cy.json requires element IDs(#2805)

---

debug/init.js
documentation/demos/edge-types/cy-style.json
documentation/demos/edge-types/data.json
documentation/md/style.md
src/extensions/renderer/base/coord-ele-math/edge-control-points.js
src/extensions/renderer/canvas/drawing-edges.js
src/style/properties.js

Adds a new `edge-style` property, may be `line` (default), or `triangle`.
Closes #2883

Add edge-style property

---

documentation/docmaker.json
documentation/md/collection/bellmanFord.md
src/collection/algorithms/bellman-ford.js
test/collection-algorithms.js

**Issue type**
Feature request
Adds a new option to the Bellman-Ford algorithm called `findNegativeWeightCycles`. If this option is set to `true`, negative weight cycles will be identified and returned.
The `negativeWeightCycles` property in the return of the algorithm should be an array with all negative weight cycles found. Each cycle is a collection in the form `[node, edge, node, edge, ...]`, the last element being the same node as the first.

Find negative weight cycles on Bellman-Ford

---

src/style/apply.js

Associated issues: #3012
- Invalidates the bounding box cache for bundled bezier edges if one of them is set to display: none, or if display: none is removed.
**Checklist**
Author:
Reviewers:

Update bundled beziers when setting display: none

---

documentation/index.html
documentation/md/notation.md
documentation/md/selectors.md

A little language cleanup in the docs to disambiguate compound nodes and compound node styling from edges.
Closes #3092 
**Checklist**
Author:
Reviewers:

Update docs re edge styling in compound contexts

---

src/extensions/layout/breadthfirst.js

Associated issue: https://github.com/cytoscape/cytoscape.js/issues/3099
Implement a solution to above-linked issue.
Author:
Reviewers:

add acyclic option to breadthfirst layout

---

documentation/index.html
documentation/md/core/style.md

Issue: https://github.com/cytoscape/cytoscape.js/issues/3098
- Adds an example to the docs of appending to a stylesheet with a string using `append()` on `cy.style()`
**Checklist**
Author:
Reviewers:

Add example of appending to stylesheet with string

---

src/collection/algorithms/k-clustering.js
src/extensions/layout/cose.js
src/extensions/renderer/base/load-listeners.js
src/extensions/renderer/canvas/layered-texture-cache.js

There are small typos in:
- src/collection/algorithms/k-clustering.js
- src/extensions/layout/cose.js
- src/extensions/renderer/base/load-listeners.js
- src/extensions/renderer/canvas/layered-texture-cache.js
Fixes:
- Should read `otherwise` rather than `otherise`.
- Should read `nonexistent` rather than `nonexistant`.
- Should read `associated` rather than `assciated`.
- Should read `ancestors` rather than `ancesters`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

documentation/index.html
documentation/md/style.md
src/extensions/renderer/base/images.js
src/style/properties.js

Associated issues: #3073
- This PR adds a feature to add the cross-origin value of 'null' for background-images.
**Checklist**
Author:
Reviewers:

Add cross-origin 'null' for background-image

---

documentation/demos/node-types/data.json
documentation/index.html
documentation/md/style.md
src/extensions/renderer/base/node-shapes.js
src/style/properties.js

Associated issues: #[3123](https://github.com/cytoscape/cytoscape.js/issues/3123)
- This PR adds a new shaped called `right-rhomboid`
**Checklist**
Author:
Reviewers:

New Shape - Right Slanting Rhomboid

---

src/extensions/layout/cose.js

**Cross-references to related issues.**
Associated issues: #3121 
The COSE layout internally uses two variables in addition to the bounding box, `clientWidth` and `clientHeight`.  They are set by default to the viewport extent.  COSE uses these variables in some places in lieu of the `boundingBox`.  Here, we set the `clientWidth` and `clientHeight` to be whatever is specified as the `boundingBox` so there is no inconsistency.
This makes the demo at https://jsbin.com/tuculav behave as expected, with a consistent result each time.
**Checklist**
Author:
Reviewers:

Make built-in COSE make better use of the specified bounding box

---

documentation/demos/multiple-windows/code.js
documentation/demos/multiple-windows/index.html
documentation/demos/multiple-windows/style.css
documentation/demos/multiple-windows/windowIndex.html
documentation/docmaker.json
src/core/index.js
src/core/viewport.js
src/extensions/renderer/base/coord-ele-math/coords.js
src/extensions/renderer/base/index.js
src/extensions/renderer/base/load-listeners.js
src/style/container.js

Associated issues: #3129
- This PR changes reference to `window` into reference to `window` of the container into which is the cytoscape rendered. This is done via changing the `window` reference into `container.ownerDocument.defaultView`. 
- This adds a demo page which demonstrates the behaviour for multiple windows. 
**Checklist**
Author:
Reviewers:

Add support for rendering cytoscape into WindowProxy document.

---

src/extensions/renderer/base/load-listeners.js

**Cross-references to related issues.**  
Associated issues: #3137
This PR fixes an issue which occurs when using touch devices.   
- The originally occurring error originated in an array access (ie [`if( r.touchData.startPosition[0] == earlier[0] ...`](https://github.com/cytoscape/cytoscape.js/blob/a46764fd7acd91fdd93ce9efcc624e67354290e4/src/extensions/renderer/base/load-listeners.js#L1689C44-L1689C44), [`if(... && startPosition[i] && ...)`](https://github.com/cytoscape/cytoscape.js/blob/a46764fd7acd91fdd93ce9efcc624e67354290e4/src/extensions/renderer/base/load-listeners.js#L1726C46-L1726C46) while startPosition was set to null instead of its initial value [null, null, null, null, ...]
- The correct initial value for `startPosition` is …

Bugfix touch interaction - adds correct reset value to startPosition

---

documentation/demos/edge-arrows/data.json

The chevron arrow was added to cytoscape.js in 2018 but has not been included in the online demo. 
Associated issues: #3148
The PR adds the arrow: "none" seems like a special case, so I have left "none" at the end of the page and made chevron the penultimate example.
**Checklist**
Author:
Reviewers:

Add chevron arrow to edge-arrows documentation

---

debug/tests.js
src/extensions/renderer/base/index.js
src/style/properties.js

Associated issues: #3021
The pull request fixes issue #3021 
The base renderer keeps a cache of "interactive" elements along with the z-order cache. Changing 'events' style property of an element changes its interactivity, but this cache is not updated. This pull request clears the cache when the 'style' event occurs.
The cache is created here: https://github.com/cytoscape/cytoscape.js/blob/658aed7234ef9d66e546af23c5134b3571c3c502/src/extensions/renderer/base/coord-ele-math/z-ordering.js#L43
Its used here:
https://github.com/cytoscape/cytoscape.js/blob/658aed7234ef9d66e546af23c5134b3571c3c502/src/extensions/renderer/base/coord-ele-math/coords.js#L94
And affects this return value:
https://github.com/cytoscape/cytoscape.js/blob/658aed7234ef9d66e546af23c5134b3571c3c502/src/extensions/renderer …

Clear z-order cache on style change.

---

documentation/md/style.md
src/extensions/renderer/base/coord-ele-math/edge-control-points.js
src/style/properties.js

**Cross-references to related issues.**  
Associated issues:
-  #3157
- This change allows bundled bezier edges, unbundled bezier edges, and segment edges to use `edge-distances: endpoints`.
- The documentation has been updated accordingly.
- The change is minimally invasive by making a new function for the adjustment.
- The adjustment alters the midpoint and the inverted normal vector used for middle-point calculations (e.g. bezier control points).
- Limitation: The adjustment must happen at the middle-point phase, rather than the endpoint phase.  The endpoint phase happens after the middle point phase, because many edges have automatic endpoints based on the middle points.  This means that the endpoint calculations would be duplicated for …

Add support for `edge-distances:endpoints`

---

documentation/docmaker.json

See issue
- https://github.com/cytoscape/cytoscape.js/issues/3169
Associated issues: #3169
**Summary Notes**
- This PR changes one word in **docmaker.json** (`ungrabbale ` to `ungrabbable`)
- Since this PR modify documents, tests are not neccesary. 
**Checklist**
Author:
Reviewers:

docs: Fix a typo

---

documentation/md/style.md
src/style/properties.js

- #3160
- Revise `z-index` property to use a `nonNegativeNumber` type rather than `nonNegativeInt`.
- Revise documentation accordingly.
- N.b. this does not change the non-negative constraint on the z-index values.
- This has been manually verified on the debug page.
**Checklist**
Author:
Reviewers:

Add support for float numbers (positive & negative) in the z-index style property

---

src/extensions/layout/cose.js

Associated issues: #3170
- This PR filters the elements passed in the layout options to discard any edge that has a connected node (source or target) that is not in the passed-in node collection.
**Checklist**
Author:
Reviewers:

Fixes COSE TypeError by filtering the edges in the passed-in options

---

src/extensions/layout/preset.js

Ref: Add official support for spacingFactor in the preset layout #3172
Associated issues:
- #3172
- This PR documents the existing support for the `spacingFactor` option within the `preset` layout.
- The `spacingFactor` can be used to compress or expand a preset layout, as required for bubble expanding/collapsing in [Enrichment Map …

Document `spacingFactor` for `preset` layout

---

documentation/md/style.md

Associated issues:
- #3160
- Add notes re. negative z-index values.
- See https://github.com/cytoscape/cytoscape.js/issues/3160#issuecomment-1776085849
**Checklist**
Author:
Reviewers:

Add note re. z-index and layering -- not like CSS proper

---

debug/tests.js
src/style/apply.js
src/style/properties.js

Associated issues: #3070
- Fix for bug #3070 
- Clears the style cache for edges connected to a node when the 'display' property changes.
- Adds the testcase created by @drauggres to the tests.js file.
**Checklist**
Author:
Reviewers:

Clear style cache for connected edges when 'display' property changed.

---

documentation/md/style.md
src/collection/dimensions/bounds.js
src/extensions/renderer/canvas/drawing-nodes.js
src/style/apply.js
src/style/properties.js

Associated issues: https://github.com/cytoscape/cytoscape.js/issues/3156
Adds node outlines as described in #3156. Pushed this one up a bit early, but will be monitoring the associated issue and integrate any feedback that comes in.
Reiterating the feature as laid out in the issue description, node outlines support the same properties as borders, but with the addition of an `outline-offset` prop, and are drawn outside the border/node shape. 
Much of the implementation mirrors how borders are rendered, but because outlines are drawn outside the border/node, the node shape needs to be redrawn at a slightly larger size than the core, filled shape. For that reason, I opted to move the path caching to a `getPath` method that both the shape rendering and `drawOutline` function can use, rather …

Node outlines

---

debug/init.js
documentation/md/style.md
package-lock.json
src/extensions/renderer/canvas/drawing-edges.js
src/style/properties.js

Associated issues: #3191 
- This PR adds a new style property on edges `<position>-arrow-width` which allow user to customise the thickness of the hollowed arrow shapes stroke. 
- default value : 'match-line' ==> the stroke width is the same as the edge width
- number value ==> considered as a px width
- string value ==> `${number}${unit}` where unit can either be `px`, `em` or `%`. 
- `%` value is based on edge width. e.g. 100% ahas the same behaviour as 'match-line'
- This PR includes modifications to the documentation to present the new property
- This PR includes modifications to the debug to easily visualise the impact of the property
**Checklist**
Author:
Reviewers:

:sparkles: Add <position>-arrow-width property for hollow shapes

---

documentation/md/style.md
src/style/apply.js

- #3196
- #2789
- Adds back documentation for pie chart properties.
- Removes deprecation warning in the console when the pie chart properties are used.
**Checklist**
Author:
Reviewers:

Reverse deprecation of pie chart props

---

debug/tests.js
src/extensions/renderer/canvas/drawing-label-text.js

- #3093
PR does this...
- Draws the text border correctly when  'text-background-shape' is set to 'round-rectangle'
- Adds a test to the demo tests
**Checklist**
Author:
Reviewers:

Draw text border for 'text-background-shape':'round-rectangle'

---

rollup.config.js

https://github.com/cytoscape/cytoscape.js/issues/3217
This pull request changes rollup config to bundle deps into the non min version of ESM.
why:
* browsers can't import cjs, so all deps must be esm
* not all deps to cytoscape are served as esm

Change rollup.config to bundle deps in esm.js

---

package.json

- #3239
Mermaid.js imports Cytoscape.js as follows (see [source](https://www.npmjs.com/package/mermaid/v/9.4.3?activeTab=code), line 3):
```ts
import cytoscape from "cytoscape/dist/cytoscape.umd.js";
```
Cytoscape version `3.29.0` introduced an [explicit `exports` field](https://github.com/cytoscape/cytoscape.js/compare/v3.28.1...v3.29.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), which misses the required `umd` export, and prevents Mermaid from loading Cytoscape.
While Cytoscape version `3.29.1` [corrected the ESM and CJS exports](https://github.com/cytoscape/cytoscape.js/compare/v3.29.0...v3.29.1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), the UMD export was still …

fix(umd): exported cytoscape.umd, closes #3239

---

debug/init.js
src/extensions/renderer/base/coord-ele-math/labels.js

**Cross-references to related issues.** 
- #3235 
- This PR ensure that separators from the original labels are kept when wrapping
**Checklist**
Author:
Reviewers:

Keep original separator instead of using space when text-wrapping

---

.gitignore
documentation/demos/6000-elements/index.html
documentation/demos/circle-layout/index.html
documentation/demos/concentric-layout/index.html
documentation/demos/cose-bilkent-layout-compound/index.html
documentation/demos/cose-bilkent-layout/index.html
documentation/demos/cose-layout/index.html
documentation/demos/edge-arrows/index.html
documentation/demos/edge-types/index.html
documentation/demos/genemania-export/index.html
documentation/demos/grid-layout/index.html
documentation/demos/labels/index.html
documentation/demos/node-types/index.html
documentation/demos/performance-tuning/index.html
documentation/demos/radius-types/index.html
documentation/demos/spread-layout/index.html
documentation/docmaker.json
package.json

- #3259
- #3257
- This PR fixes that `cytoscape.min.js` gets copied into `documentation/js/build` instead of `documentation/js` due to a breaking change in `cpy-cli>=4.0.0` introduced by #3247
> Remove the --parents flag. The copy is now recursive by default. To get flat output, use the --flat flag.
- This PR replaced the `polyfill.io` cdn links with the corresponding `cloudflare` cdn links since `polyfill.io` is a [known potential security risk](https://www.veracode.com/blog/security-news/polyfill-supply-chain-attack-what-it-and-how-know-if-youre-affected).
- This PR replaces …

📚🩹 Fix broken demos in the docs are broken due to 404 error fetching `cytoscape.min.js`

---

src/extensions/renderer/base/coord-ele-math/edge-control-points.js

- #3267
- Fixes the getSegmentPoints ()and getControlPoints() functions.
- There's a bit of a chicken-and-egg problem with the way those functions were written. It checks the edgeType field before calling recalculateRenderedStyle(), but recalculateRenderedStyle() initializes the edgeType field.
- The fix moves the call to recalculateRenderedStyle() to before the edgeType check, so it always gets called. The getEdgeMidpoint() function works that way so I assume its fine. I opened a PR for this simple fix because I'm not entirely sure.
**Checklist**
Author:
Reviewers:

initialize edgeType when calling getSegmentPoints or getControlPoints

---

src/collection/dimensions/bounds.js
src/extensions/renderer/canvas/index.js

- #3271
- Now when the label rotation offset is calculated it includes the margin/outline/border/padding that is part of the label bounds.
- I don't know if this is the best way to fix the bug. I didn't want to change anything about how the bounding boxes are calculated or saved because I'm concerned I might break something. So instead it saves the "padding" along with the bounding box and uses it when calculating the rotation offset.
**Checklist**
Author:
Reviewers:

Add padding to getLabelRotationOffset()

---

src/extensions/renderer/base/load-listeners.js

- #3273 
Notes re. the content of the pull request. Give context to reviewers or serve as a general record of the changes made. Add a screenshot or video to demonstrate your new feature, if possible.
- This PR attaches the 'mousemove' handler to both the window and the shadow DOM root of the cytoscape container if there is one.
The problem is described in detail in #3273, but I will recap here. The 'mousemove' handler is attached to the window, but it uses a function called `eventInContainer()` to test if the mouse is over the cytoscape container. The problem is that when the canvas is inside a shadow DOM the event.target field is retargeted to the shadow root, and the `eventInContainer()` function can't tell that the event was over the container. This prevents the …

Attach the 'mousemove' handler to the window and the shadow DOM root.

---

src/extensions/layout/breadthfirst.js

- #3288 
- #3289 
- #3290 
**Notes
- This PR fixes all the issues above from:
https://github.com/user-attachments/assets/60891331-e04f-4d62-8d8a-40264131c404
- This PR fixes all the issues above to:
https://github.com/user-attachments/assets/cd39db4d-6365-411d-9798-a42cc9e48d23
- This PR updates `let` variable declarations to `const`, when appropriate,  in `src/extensions/layout/breadthfirst.js`
**Checklist**
Author:
Reviewers:

Fix breadthfirst layout to center all rows vertically and each row horizontally; and to respect a given bounding box

---

package-lock.json
src/extensions/layout/breadthfirst.js

- #3293 
**Notes
- This PR fixes the issue above, from:
https://github.com/user-attachments/assets/a3f78a3f-efd2-48de-b390-6f07840fe2ee
- This PR fixes the issue above, to:
https://github.com/user-attachments/assets/0e18b170-ab39-4ffa-84be-1251adff0a18
**Checklist**
Author:
Reviewers:

Fix breadthfirst layout to stay inside viewport on fit: false and no boundingBox

---

src/extensions/renderer/canvas/webgl/atlas.js
src/extensions/renderer/canvas/webgl/defaults.js
src/extensions/renderer/canvas/webgl/drawing-elements-webgl.js
src/extensions/renderer/canvas/webgl/drawing-redraw-webgl.js

- #3320
- Fixes issue where the webgl mode was still displaying nodes/edges that had the `visibility:hidden` property.
- Selection seems to work fine. I think it wasn't working for the nodes that were supposed to be hidden.
**Checklist**
Author:
Reviewers:

fix webgl mode showing hidden nodes/edges

---

debug/init.js
src/extensions/renderer/base/coord-ele-math/edge-control-points.js

- #3322 
- #3309 
- Fixes the issue specified in #3322.
- Cleans up the debug page so it's easier to see.  It looks like it got complicated over several previous PRs.
- The fix is to just use a different key in the table for unbundled edges.
Debug page **before**:
Debug page **after**:
You can see in the debug page (`npm run watch`) that the …

Put unbundled edges in a separate key in the control point table

---

debug/init.js
playwright-tests/renderer.spec.js
src/extensions/renderer/base/coord-ele-math/edge-control-points.mjs

**Cross-references to related issues.**  
- #3318 
- This PR fixes the issue by covering cases when points are collinear and therefore corner radius = 0 ( essentially avoiding division by 0 leading to label being placed at [NaN, NaN])
**Checklist**
Author:
Reviewers:

:bug: Fix #3318 label not shown in specific case with round-segments

---

debug/webgl/network-styles.json
src/extensions/renderer/canvas/webgl/defaults.mjs
src/extensions/renderer/canvas/webgl/drawing-elements-webgl.mjs
src/extensions/renderer/canvas/webgl/drawing-redraw-webgl.mjs

- This PR fixes bug #3337 
- Unfortunately the idea to set the background opacity of labels to 0.0001 did not work. I don't know why, but it would not detect the clicks when I tried this. Maybe something in WebGL ignores small alpha values. I'm not sure.
- Instead I took an approach of reusing the "simple shapes" mode that draws rectangles. If `text-events: no` then it will ignore the label, if `text-events: yes` then it will render the bounding box of the label as an opaque rectangle that can be clicked on. Of course you can't see this because its happening in an offscreen framebuffer.
- I didn't try measuring but this may actually be more performant. It doesn't have to render label textures anymore for picking. Labels are either ignored or rendered as rectangles.
**Checklist**
Author: …

WebGL: fix label picking

---

src/extensions/renderer/base/coord-ele-math/labels.mjs

- #3270 (addresses this)
- #3298 (supersedes this)
- Remove caching in BRp.calculateLabelDimensions: This removes caching on the text level, which is used for things like multiline calculations).  This can use a fair bit of memory.
- Cache label dims in BRp.applyPrefixedLabelDimensions instead.  
- The label dimensions are already stored for use …

Higher-level caching for label dimensions

---

src/extensions/renderer/base/coord-ele-math/edge-control-points.mjs

- #3280 
- #3251
Just reapplies Dylan's changes cleanly on the unstable branch.
**Checklist**
Author:
Reviewers:

Reapply @d2fong's change re. : Unbundled bezier edge disappear or flip when nodes are close #3251

---

index.d.ts

- #3339
- Adds the type definition for `cy.renderedExtent()`
**Checklist**
Author:
Reviewers:

Add `cy.renderedExtent()` to types

---

playwright-tests/renderer.spec.js
src/collection/dimensions/bounds.mjs

- #3251
- #3349
- Add tests re. initial zero bounding box
- `cachedBoundingBoxImpl()` no longer checks the element state.  It just sets the cache values and returns the end result.
- `eles.boundingBox()` checks a memoized `isDirty()` function.  This is useful for getting the dirty state of edges before nodes.
- It's now easier to read, and the …

Simplify the bounding box implementation

---

package-lock.json
package.json
playwright-tests/renderer.spec.js
src/extensions/renderer/base/coord-ele-math/edge-control-points.mjs

- #3364
FIx: Bezier control points seems incorrect in version 3.31.2 #3364
Ref: 85ad43f
Ref: Reapply @d2fong's change re. : Unbundled bezier edge disappear or flip when nodes are close #3251
@mikael.konradsson @dwchMikael
**Checklist**
Author:
Reviewers:

FIx: Bezier control points seems incorrect in version 3.31.2 #3364

---

index.d.ts
src/extensions/layout/breadthfirst.mjs
src/util/index.mjs
src/util/position.mjs

**Cross-references to related issues.** 
- https://github.com/cytoscape/cytoscape.js/issues/3369
- This PR allows breadthfirst layout to  draw 'left-right', 'right-left', and 'bottom-top' tree, in addition to the default 'top-bottom'.
Top-bottom:
Bottom-top:
Left-right:
Right-left:
**Checklist**
Author:
Reviewers:

Add a 'direction' option for breadthfirst layout that can be 'top-bottom', 'bottom-top', 'left-right', or 'right-left'

---

src/extensions/renderer/base/coord-ele-math/coords.mjs

- #3372
- This PR fixes a JS TypeError that prevents a node from being selected when:
a.  no `label` style has been specified; or
b. the node does not have a label
**Checklist**
Author:
Reviewers:

Bug fix for box selection of nodes without labels

---

documentation/md/layouts/breadthfirst.md
index.d.ts
src/extensions/layout/breadthfirst.mjs

Fix the enum values of breadthfirst's direction option so they're more consistent with other properties. Change to the following:
- downward
- upward
- rightward
- leftward
**Cross-references to related issues.** 
- https://github.com/cytoscape/cytoscape.js/issues/3369
- https://github.com/cytoscape/cytoscape.js/pull/3373
- Renaming of the enum values based on @maxkfranz comment
- https://github.com/cytoscape/cytoscape.js/pull/3373#issuecomment-2955979295
**Checklist**
Author:
Reviewers:

Fix the enum values of breadthfirst's direction option to *ward

---

src/extensions/renderer/base/load-listeners.mjs

- #3394
- Zero deltas are now ignored in the `wheel` handler of the renderer.
**Checklist**
Author:
Reviewers:

Ignore zero deltas for `wheel` events

---

src/extensions/renderer/canvas/webgl/drawing-elements-webgl.mjs

- #3365
- Adds a guard in `ElementDrawingWebGL.drawTexture()` for invalid edges.
**Checklist**
Author:
Reviewers:

Add webgl edge guard in texture getter
