cytoscape/cytoscape.js

documentation/md/style.md, src/extensions/renderer.canvas.drawing-label-text.js, src/style.js
@maxkfranz @kurniaikhwan 
This is the new text wrapping feature pull request, which should have fixed the glitches in previous pull request.
Note that for a better looking graph, we do not wrap text for edge label text.
=> Wrap text pull request

documentation/index.html, documentation/md/style.md, src/extensions/renderer.canvas.drawing-label-text.js, src/style.js
So rounded corners are now optional for the label background. My editor removed some spaces on empty lines, sorry about that!
=> #849 Added a text-background-shape property

src/extensions/layout.spread.js
=> Fixed the problem with spread layout not working in minified

src/extensions/renderer/base/images.js
=> Prevent tainted canvas

documentation/md/style.md, src/extensions/renderer/base/coord-ele-math.js, src/style/properties.js
Add the ability to draw single-line labels that are ellipsized instead of wrapped.
=> Add 'ellipsize' options to text-wrap

src/extensions/layout/breadthfirst.js
This is a bugfix for #1634. The majority of the details are mentioned in the issue.
=> Fix bug in breadthfirst layout for a collection of elements

CONTRIBUTING.md
Reverts cytoscape/cytoscape.js#1699
=> Revert "Added references to Github fork and PR docs #1643"

documentation/md/core/init.md
From issue https://github.com/cytoscape/cytoscape.js/issues/1734.
=> Added note about cy init and custom fonts #1734

src/extensions/renderer/base/coord-ele-math/coords.js
Solves issue brought up in #1583.
=> If selection box is contained in parent do not select #1583

debug/init.js, documentation/md/style.md, src/extensions/renderer/base/coord-ele-math/nodes.js, src/extensions/renderer/base/node-shapes.js, src/extensions/renderer/canvas/drawing-shapes.js, src/extensions/renderer/canvas/node-shapes.js, src/math.js, src/style/properties.js
- adds a new compound shape
- adds quadratic bezier related functions to math (solve quadratic, quadratic bez pts to coefficients)
- uses barrel points for approximate line intersection
=> barrel shape implementation

src/extensions/renderer/base/node-shapes.js, src/extensions/renderer/canvas/drawing-shapes.js, src/math.js
- renames cp0, cp1 to more accurately describe what the values represent
- barrel draw, intersect, and check point all use the same function to get the curve constants
=> barrel shape draw, check point, and line intersection use the same function

.eslintrc.json, documentation/md/style.md, src/extensions/renderer/base/node-shapes.js, src/extensions/renderer/canvas/drawing-shapes.js, src/extensions/renderer/canvas/node-shapes.js, src/math.js, src/style/properties.js
Adds three new shapes
- bottomroundrectangle
- tag
- concave hexagon
=> concavehexagon, tag, bottomroundrectangle shape implementations

.babelrc, .eslintrc.json, gulpfile.js, package.json, webpack.config.js
adds webpack tooling to enable external dependency compatibility.
=> Use webpack

documentation/docmaker.json, documentation/md/collection/layoutPositions.md, documentation/md/collection/merge.md, documentation/md/collection/unmerge.md, documentation/md/style.md, src/extensions/layout/breadthfirst.js, src/extensions/layout/circle.js, src/extensions/layout/concentric.js, src/extensions/layout/cose.js, src/extensions/layout/grid.js, src/extensions/layout/preset.js, src/extensions/layout/random.js
- document the `animateFilter()` option in `layoutPositions()`, and each bundled layout
- document the `transform()` option in `layoutPositions()`, and each bundled layout
- document svg considerations when using svg images for node body background
- document `eles.merge()` and `eles.unmerge()`
=> 3.2 milestone documentation

documentation/md/style.md, src/extensions/renderer/base/coord-ele-math/edge-control-points.js, src/style/properties.js
=> Add explicit specification of a straight edge style #1668

documentation/docmaker.json, documentation/md/core/mount.md, documentation/md/core/unmount.md, src/core/index.js, src/core/renderer.js, src/extensions/renderer/base/index.js, src/extensions/renderer/null/index.js
- This branch still needs testing, I am opening this PR to get your feedback about implementation i.e should it be implemented like this or not.
- adds mount() to the core
- adds unmount() to the core
- mount can be called multiple times
- ~~~changes the Core constructor to wrap a coreInit function. coreInit handles all of the things that were previously handled in the Core constructor.~~~
- ~~~coreInit is a common function used by both mount and the Core constructor~~~
- mount mutates renderer options
=> Multi mount

src/core/index.js, test/core-graph-manipulation.js
As this is a bugfix, i'm setting it to master. 
Please let me know if should change that.
Ref #2231
=> Fixes a bug introduced by removing elements in a for 0 -> eles.length

src/collection/element.js
Simple fix to change the order of creation of the emitter.
=> Fix #2313 - bug that causes an emit before emitter is created.

src/collection/index.js
More information in Issue #2417
=> Fix degree of node with loop

documentation/md/style.md, src/extensions/renderer/canvas/drawing-images.js, src/style/properties.js
=> feat(style): makes `background-clip` to support multiple values

documentation/md/style.md, src/collection/dimensions/bounds.js, src/math.js, src/style/properties.js, test/math.js, test/modules/math.js
This is done by accepting 1, 2 or 4 params.
Related to #2497
=> Allow bounds-expansion to set a different size for each side

documentation/docmaker.json, documentation/md/collection/tarjanStronglyConnected.md, src/collection/algorithms/index.js, src/collection/algorithms/tarjan-strongly-connected.js, test/collection-tarjan-strongly-connected.js
This PR adds Tarjan's algorithm for finding the [strongly connected components](https://en.wikipedia.org/wiki/Strongly_connected_component) of a directed graph, as proposed in #2582.
=> Add strongly connected components algorithm

src/extensions/renderer/canvas/drawing-edges.js
=> Fix Firefox edge arrow performance

documentation/md/collection/selectify.md
**Issue type**
Typo
_IMHO: I know this PR doesn't mean much and could be a bit picky, but before anyone else is confused about it, I thought it might be better to fix it._
=> docs: fix typo in code example

documentation/md/collection/on.md
=> docs(collection): add details about events on elements

src/extensions/renderer/canvas/ele-texture-cache.js
See https://github.com/cytoscape/cytoscape.js/issues/2770
=> Short circuit when `bb` is not defined

dist/ts-definations/types.d.ts, documentation/docmaker.json, documentation/generateDocs.js, src/animation.js, src/collection/class.js, src/collection/comparators.js, src/collection/compounds.js, src/collection/filter.js, src/collection/group.js, src/collection/iteration.js, src/collection/layout.js, src/collection/style.js, src/collection/traversing.js, src/core/add-remove.js, src/core/index.js, src/core/layout.js, src/core/notification.js, src/core/search.js, src/core/style.js, src/core/viewport.js, src/extensions/layout/index.js
This PR will fix the Typescript Definition file.
=> replaced @namespace with @methodName

src/collection/algorithms/a-star.js, test/collection-astar-edges.js, test/collection-astar.js
Added two tests to demonstrate #2830. They will cause the build to fail.
=> Fix and tests for #2830

src/util/index.js
https://github.com/cytoscape/cytoscape.js/issues/2828
=> Issue-2828: Fixed the issue with retired textures

.github/CONTRIBUTING.md
small grammatical changes to the CONTRIBUTING.md file
=>  modified CONTRIBUTING.md file by altering the grammar for better readability 

documentation/md/getting-started.md
small grammatical changes to the getting-started.md file
=> modified getting-started.md file with a minor grammar fix

documentation/md/core/init.md, documentation/md/events.md, src/core/index.js, src/core/viewport.js, src/extensions/renderer/base/load-listeners.js
This PR allows listening for a double-click event when setting doubleClickEnabled flag to true in the main cytoscape class configuration. By default, the single-click debounce time is given 250ms, and can be changed using clickDebounceTime property.
=> Add double-click feature

documentation/docmaker.json, documentation/md/collection/boundingBox.md, src/collection/dimensions/bounds.js
=> Include underlay into bounding box

src/selector/tokens.js, test/selectors.js
[CSS style selectors with multiple classes are not parsed correctly](https://github.com/cytoscape/cytoscape.js/issues/2995)
=> Fix css class selector.

package-lock.json, package.json, src/define/data.js, src/util/timing.js
Associated issues: #3043
- Switches to latest lodash
**Checklist**
Author:
Reviewers:
=> issue 3043, upgrade to latest non module lodash

src/collection/algorithms/betweenness-centrality.js, src/collection/algorithms/bfs-dfs.js, src/collection/algorithms/closeness-centrality.js, src/collection/algorithms/degree-centrality.js, src/util/index.js
Provides some typo fixes. Does not affect code execution
**Checklist**
Author:
- [ x] The proper base branch has been selected.  New features go on `unstable`.  Bug-fix patches can go on either `unstable` or `master`.
- [ x] Automated tests have been included in this pull request, if possible, for the new feature(s) or bug fix.  Check this box if tests are not pragmatically possible (e.g. rendering features could include screenshots or videos instead of automated tests).
- [ x] The associated GitHub issues are included (above).
- [x ] Notes have been included (above).
Reviewers:
=> Spelling Fixes

documentation/index.html
The layer5 community currently uses Cytoscape.js on some of of primary projects like 
- [MeshMap](https://layer5.io/cloud-native-management/meshmap)
Associated issues: #3103 
- This PR adds Layer5 to the list of Cytoscape.js
**Checklist**
Author:
Reviewers:
=> Added Layer5 to one of the Big-name tech currently using Cytoscape.js

src/extensions/renderer/base/index.js
This makes the code compatible with Trusted Types.
**Checklist**
Author:
Reviewers:
=> Use textContent instead of innerHTML

README.md
=> Fix non-valid html5 img tag in README.md

.github/ISSUE_TEMPLATE/bug_report.md
Ref: Add documentation for how to create a JSBin #3316
- #3316
- Updates the issue template with steps on how to create a JSBin reproducible demo.
**Checklist**
Author:
Reviewers:
=> Update the bug report template with JSBin steps

package.json
> **Cross-references to related issues.**  If there is no existing issue that describes your bug or feature request, then [create an issue](https://github.com/cytoscape/cytoscape.js/issues/new/choose) before making your pull request.
Happy to create a new issue first, if needed (the change seems to be too small for this).
- N/A
After removing [`@types/cytoscape`](https://www.npmjs.com/package/@types/cytoscape) from the repo and running `tsc` to lint code, I faced this error:
```
TS7016: Could not find a declaration file for module 'cytoscape'. '/path/to/project/node_modules/cytoscape/dist/cytoscape.esm.mjs' implicitly has an 'any' type.
There are types at '/path/to/project/node_modules/cytoscape/index.d.ts', but this result could not be resolved when respecting …
```
=> Expose typings via package.json → exports

README.md, documentation/md/links.md
- #3343
- They removed support for the `c` context argument, which is where the context of "I'm using Cytoscape.js" was specified.
- This fix just puts everything in the `q` argument.
- New link: https://www.phind.com/search?q=I%27m%20using%20the%20Cytoscape.js%20graph%20theory%20JS%20library.%20How%20do%20I%20create%20a%20graph%20in%20my%20HTML%20pa …
=> Fix the Phind 'get help' badge link.

src/collection/dimensions/width-height.mjs, test/collection-style.mjs
- #3350
- Fixes #3350.
**Checklist**
Author:
Reviewers:
=> fix node.outerWidth/Height() to respect 'border-position'

documentation/demos/pie-style/code.js, documentation/demos/stripe-style/code.js, documentation/demos/stripe-style/index.html, documentation/demos/stripe-style/style.css, documentation/md/style.md, index.d.ts, src/extensions/renderer/canvas/drawing-nodes.mjs, src/style/apply.mjs, src/style/index.mjs, src/style/properties.mjs
- #3340 
- #3341
- Not quite ready to be merged yet.  Waiting on feedback & API finalisation.
- Any ideas for automated tests related to this welcome.
- Adds ring chart support by using the existing pie chart properties and adding a property to allow for the radius of the centre, `pie-hole`.
- Adds support for stripe charts.  
- Updated docs in …
=> Ring & stripe charts

src/extensions/renderer/base/load-listeners.mjs
- #3336 
- Workaround for imprecise mice
- Heuristic to detect lousy mice: Sample 4 events: all wheel events in sample are `%5 == 0` OR all wheel events in sample have same large magnitude
- When heuristic true: Apply detected scaling factor to new wheel events
- Update the heuristic and scaling factor ongoing, just in case the sample was unlucky
- …
=> Imprecise mouse wheel workaround
